// @ts-nocheck
  // This file is autogenerated by scripts/build-registry.ts
  // Do not edit this file directly.
  import * as React from "react"
  
  export const Index: Record<string, any> = {
    "changesets": {
      "changesets": {
        name: "changesets",
        description: "",
        type: "registry:generator",
        registryDependencies: undefined,
        files: [{
          path: "registry/changesets/.github/workflows/npm-release.yml",
          type: "registry:file",
          target: ""
        }],
        source: "",
        meta: undefined,
      },
    },
  }
  