interface PullRequest {
  html_url: string;
  number: number;
}

export async function createPullRequest(
  repoFullName: string,
  githubToken: string,
  branch: string,
  issueNumber: number,
  issueTitle: string | null,
  summary: string
): Promise<PullRequest> {
  const title = `fix: ${issueTitle ?? `issue #${issueNumber}`}`;
  const body = [
    summary,
    '',
    `Closes #${issueNumber}`,
    '',
    '*Generated by [thinkthroo-daemon](https://github.com/ramu-narasinga/thinkthroo)*',
  ].join('\n');

  // Detect default branch
  const repoRes = await fetch(`https://api.github.com/repos/${repoFullName}`, {
    headers: { Authorization: `token ${githubToken}`, Accept: 'application/vnd.github+json' },
  });
  const repoData = await repoRes.json() as { default_branch: string };
  const base = repoData.default_branch ?? 'main';

  const res = await fetch(`https://api.github.com/repos/${repoFullName}/pulls`, {
    method: 'POST',
    headers: {
      Authorization: `token ${githubToken}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ title, body, head: branch, base }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as { message?: string };
    throw new Error(`Failed to create PR: ${err.message ?? res.status}`);
  }

  return res.json() as Promise<PullRequest>;
}
